import { useBrand, useMediaQuery } from '@westpac/core';
import PropTypes from 'prop-types';
import { useMemo } from 'react';
import { FlexiCellHintProps } from './FlexiCellHint.types';

/** Flexi Cell Hint: Flexi Cell Hint */
export const FlexiCellHint = ({
	children,
	tag: Tag = 'p',
	truncateText,
	...props
}: FlexiCellHintProps) => {
	const { PACKS, COLORS } = useBrand();
	const mq = useMediaQuery();
	const css = useMemo(() => {
		const {
			fontSize: fontSizeXS,
			lineHeight: lineHeightXS,
			fontFamily: fontFamilyXS,
		} = PACKS.typeScale.bodyFont[10];
		const {
			fontSize: fontSizeMD,
			lineHeight: lineHeightMD,
			fontFamily: fontFamilyMD,
		} = PACKS.typeScale.bodyFont[9];

		return mq({
			fontSize: [fontSizeXS, fontSizeMD],
			lineHeight: [lineHeightXS, lineHeightMD],
			fontFamily: [fontFamilyXS, fontFamilyMD],
			fontWeight: 400,
			margin: 0,
			color: COLORS.muted,
			...(truncateText && {
				overflow: 'hidden',
				textOverflow: 'ellipsis',
				whiteSpace: 'nowrap',
			}),
		});
	}, [COLORS.muted, PACKS.typeScale.bodyFont, mq, truncateText]);

	return (
		<Tag {...props} css={css}>
			{children}
		</Tag>
	);
};

FlexiCellHint.propTypes = {
	// ----------------------------- Warning --------------------------------
	// | These PropTypes are generated from the TypeScript type definitions |
	// |     To update them edit TypeScript types and run "yarn prop-types"  |
	// ----------------------------------------------------------------------
	children: PropTypes.node,
	tag: PropTypes.oneOf([
		'a',
		'abbr',
		'address',
		'animate',
		'animateMotion',
		'animateTransform',
		'area',
		'article',
		'aside',
		'audio',
		'b',
		'base',
		'bdi',
		'bdo',
		'big',
		'blockquote',
		'body',
		'br',
		'button',
		'canvas',
		'caption',
		'center',
		'circle',
		'cite',
		'clipPath',
		'code',
		'col',
		'colgroup',
		'data',
		'datalist',
		'dd',
		'defs',
		'del',
		'desc',
		'details',
		'dfn',
		'dialog',
		'div',
		'dl',
		'dt',
		'ellipse',
		'em',
		'embed',
		'feBlend',
		'feColorMatrix',
		'feComponentTransfer',
		'feComposite',
		'feConvolveMatrix',
		'feDiffuseLighting',
		'feDisplacementMap',
		'feDistantLight',
		'feDropShadow',
		'feFlood',
		'feFuncA',
		'feFuncB',
		'feFuncG',
		'feFuncR',
		'feGaussianBlur',
		'feImage',
		'feMerge',
		'feMergeNode',
		'feMorphology',
		'feOffset',
		'fePointLight',
		'feSpecularLighting',
		'feSpotLight',
		'feTile',
		'feTurbulence',
		'fieldset',
		'figcaption',
		'figure',
		'filter',
		'footer',
		'foreignObject',
		'form',
		'g',
		'h1',
		'h2',
		'h3',
		'h4',
		'h5',
		'h6',
		'head',
		'header',
		'hgroup',
		'hr',
		'html',
		'i',
		'iframe',
		'image',
		'img',
		'input',
		'ins',
		'kbd',
		'keygen',
		'label',
		'legend',
		'li',
		'line',
		'linearGradient',
		'link',
		'main',
		'map',
		'mark',
		'marker',
		'mask',
		'menu',
		'menuitem',
		'meta',
		'metadata',
		'meter',
		'mpath',
		'nav',
		'noindex',
		'noscript',
		'object',
		'ol',
		'optgroup',
		'option',
		'output',
		'p',
		'param',
		'path',
		'pattern',
		'picture',
		'polygon',
		'polyline',
		'pre',
		'progress',
		'q',
		'radialGradient',
		'rect',
		'rp',
		'rt',
		'ruby',
		's',
		'samp',
		'script',
		'section',
		'select',
		'slot',
		'small',
		'source',
		'span',
		'stop',
		'strong',
		'style',
		'sub',
		'summary',
		'sup',
		'svg',
		'switch',
		'symbol',
		'table',
		'tbody',
		'td',
		'template',
		'text',
		'textarea',
		'textPath',
		'tfoot',
		'th',
		'thead',
		'time',
		'title',
		'tr',
		'track',
		'tspan',
		'u',
		'ul',
		'use',
		'var',
		'video',
		'view',
		'wbr',
		'webview',
	]),
	/**
	 * Define if it is going to truncate the text
	 */
	truncateText: PropTypes.bool,
};
