import React from 'react';

import * as components from '../src';

const icons = [
	'AccessibilityIcon',
	'AccountIcon',
	'AddCircleIcon',
	'AddIcon',
	'AlertIcon',
	'AndroidIcon',
	'AppleIcon',
	'ArrowLeftIcon',
	'ArrowRightIcon',
	'AtmIcon',
	'AustraliaIcon',
	'BackspaceIcon',
	'BankIcon',
	'BarChartIcon',
	'BookIcon',
	'BpayIcon',
	'BusinessPersonIcon',
	'CafeIcon',
	'CalculatorIcon',
	'CalendarIcon',
	'CameraIcon',
	'CarIcon',
	'ChatIcon',
	'ClockIcon',
	'CloseIcon',
	'CompassIcon',
	'ContactIcon',
	'CreditCardIcon',
	'CubeIcon',
	'DeleteIcon',
	'DesktopIcon',
	'DollarIcon',
	'DownloadFileIcon',
	'DownloadIcon',
	'DragIcon',
	'DropboxIcon',
	'DropDownIcon',
	'DropUpIcon',
	'EditIcon',
	'EftposIcon',
	'EmailIcon',
	'ErrorIcon',
	'ExcelFileIcon',
	'ExitIcon',
	'ExpandLessIcon',
	'ExpandMoreIcon',
	'FacebookIcon',
	'FaceHappyIcon',
	'FavouriteIcon',
	'FilterIcon',
	'FingerprintIcon',
	'FutureClockIcon',
	'GenericFileIcon',
	'GeolocationIcon',
	'GiftIcon',
	'GithubIcon',
	'GlobalIcon',
	'GooglePlusIcon',
	'GridIcon',
	'GrowthIcon',
	'HamburgerMenuIcon',
	'HeadsetIcon',
	'HelpIcon',
	'HistoryClockIcon',
	'HouseIcon',
	'IdCardIcon',
	'ImageSquareIcon',
	'InfoIcon',
	'InstagramIcon',
	'InvestIcon',
	'KeyholeIcon',
	'KeyIcon',
	'LightBulbIcon',
	'LimitIcon',
	'LinkedinIcon',
	'LinkIcon',
	'ListIcon',
	'LiveChatIcon',
	'MapIcon',
	'MapPinIcon',
	'MessageIcon',
	'MobilePayIcon',
	'MoneyInIcon',
	'MoneyOutIcon',
	'MoreHorizontalIcon',
	'MoreVerticalIcon',
	'MoveFromIcon',
	'MoveToIcon',
	'NewContentIcon',
	'NewWindowIcon',
	'NotificationActiveIcon',
	'NotificationIcon',
	'NotificationOffIcon',
	'OfficeIcon',
	'OpenBrowserIcon',
	'PadlockIcon',
	'PadlockOpenIcon',
	'PauseCircleIcon',
	'PauseIcon',
	'PayIcon',
	'PaypassIcon',
	'PayToMobileIcon',
	'PendingIcon',
	'PeopleIcon',
	'PercentIcon',
	'PersonIcon',
	'PhoneIcon',
	'PieChartIcon',
	'PlaneIcon',
	'PlayCircleIcon',
	'PlayIcon',
	'PrintIcon',
	'ProgressIcon',
	'QuickBalanceIcon',
	'ReceiptIcon',
	'RefreshIcon',
	'RemoveCircleIcon',
	'RemoveIcon',
	'RssIcon',
	'SdStorageIcon',
	'SearchIcon',
	'SecurityIcon',
	'ServiceBellIcon',
	'SettingsIcon',
	'ShareIcon',
	'ShopIcon',
	'SimCardIcon',
	'SlackIcon',
	'SmsIcon',
	'StarEmptyIcon',
	'StarHalfIcon',
	'StarIcon',
	'StopwatchIcon',
	'SuperIcon',
	'SwitchIcon',
	'TabletIcon',
	'TakeOutIcon',
	'TelephoneIcon',
	'ThumbDownIcon',
	'ThumbUpIcon',
	'TickIcon',
	'TransferIcon',
	'TransportIcon',
	'TwitterIcon',
	'UmbrellaIcon',
	'UploadIcon',
	'VerifiedIcon',
	'VideoIcon',
	'VoiceIcon',
	'WalkIcon',
	'WalletIcon',
	'WatchIcon',
	'WearableIcon',
	'WheelchairIcon',
	'WindowsNewIcon',
	'WordFileIcon',
	'WriteIcon',
	'YammerIcon',
	'YoutubeIcon',
	'ZipFileIcon',
];
const Grid = props => (
	<div
		style={{
			display: 'grid',
			gridAutoFlow: 'row',
			gridAutoRows: 'minmax(20px,auto)',
			gridGap: 8,
			gridTemplateColumns: 'repeat(12,1fr)',
		}}
		{...props}
	/>
);
const Cell = props => (
	<div
		style={{
			gridColumnEnd: 'span 3',
			gridRowEnd: 'span 3',
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			textAlign: 'center',
		}}
		{...props}
	/>
);
const Name = props => (
	<div
		style={{
			fontSize: 12,
			marginTop: 12,
		}}
		{...props}
	/>
);

export default () => (
	<Grid>
		{icons.map(s => {
			const Icon = components[s];
			return (
				<Cell>
					<Icon key={s} label={s} title={s} />
					<Name>{s}</Name>
				</Cell>
			);
		})}
	</Grid>
);
